name: CD


on:
  repository_dispatch
  push:
    branches:
      - source



jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: |
          npm ci
      - name: Configure Git machine user
        run: |
          git config --global user.name "commonly buildbot"
          git config --global user.email "build@commonlyjs.com"
      - name: Publish to GitHub pages
        run: |
          npm run publish --if-present -- --repo "https://$GH_PAGES_TOKEN:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git"
        env:
          GH_PAGES_TOKEN: ${{secrets.GH_PAGES_TOKEN}}
